# Generated by Django 5.0.3 on 2024-03-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exchangerate_date_alter_license_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='platform_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currency'),
        ),
    ]
