# Generated by Django 5.0.3 on 2024-03-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_advertiser_platform_id_alter_advertiser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.license'),
            preserve_default=False,
        ),
    ]
