# Generated by Django 5.0.3 on 2024-03-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_advertiser_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.vat'),
            preserve_default=False,
        ),
    ]
